### ISSUE TITLE
Publish to docker repository

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/yeoman-generator-list#13]

**Comment by sindresorhus** [comment]
Would you or @apobbati be able to do that? I have no idea how it work.

**Comment by SBoudrias** [comment]
We'll need a member of the core team to do it.

**Comment by SBoudrias** [comment]
FWIW, it'll now be useful for us to run this service as a docker container: https://blog.heroku.com/archives/2015/5/5/introducing_heroku_docker_release_build_deploy_heroku_apps_with_docker

**Comment by SBoudrias** [comment]
Let's not publish it to docker repo, let's just use docker for deployment on Heroku.
