### ISSUE TITLE
Generator not appearing in list

### ISSUE THREAD

**Issue by jayrenn** [yeoman/yeoman-generator-list#16]
We created a [generator](https://github.com/winjs/generator-winjs) four weeks ago with the appropriate keyword and pre-requisites. However, it is not showing up on the [online list of generators](http://yeoman.io/generators/). Looking at your source code, our generator is listed in the [npm registry](https://skimdb.npmjs.com/registry/_design/app/_view/byKeyword?startkey=[%22yeoman-generator%22]&endkey=[%22yeoman-generator%22,{}]&group_level=3), but not on your [test page](http://yeoman-generator-list.herokuapp.com/) or [main site](http://yeoman.io/generators/).

What seems to be the problem?

**Comment by kevva** [comment]
Try adding the `repository` field.
