### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by andreicristianpetcu** [yeoman/yeoman-generator-list#24]
Apparently this service is down
http://yeoman-generator-list.herokuapp.com/

And I cannot see the list of generators here
http://yeoman.io/generators/

**Comment by SBoudrias** [comment]
Fixed.

**Comment by andreicristianpetcu** [comment]
Thank you!

**Comment by ganoro** [comment]
Bump...
service is down (again)
http://yeoman-generator-list.herokuapp.com/

Thank you for your hard work guys!

**Comment by arthurvr** [comment]
Thanks for letting us know.

**Comment by arthurvr** [comment]
Fixed!

**Comment by ganoro** [comment]
thanks @arthurvr for your attention! (btw, I can't access the generator right now again)

**Comment by arthurvr** [comment]
> ! (btw, I can't access the generator right now again)

Should be fixed now.
