### ISSUE TITLE
Add download count in generator list

### ISSUE THREAD

**Issue by ericduran** [yeoman/yeoman-generator-list#3]
Related https://github.com/yeoman/yeoman.io/pull/104

**Comment by sindresorhus** [comment]
PR welcome for anyone looking here ;)

**Comment by eddiemonge** [comment]
closing https://github.com/yeoman/yeoman.io/pull/104#issuecomment-62238045.  can reopen based on result of https://github.com/yeoman/yeoman.io/issues/194
