### ISSUE TITLE
moving the blacklist here

### ISSUE THREAD

**Issue by gaboesquivel** [yeoman/yeoman-generator-list#30]
I think it would a good idea to filter the list on the server rather than filtering on each client.
filter generators and create a json file to be served.  related to https://github.com/yeoman/yeoman-generator-list/issues/19

**Comment by sindresorhus** [comment]
:+1:

**Comment by eddiemonge** [comment]
Ideally the blacklist will go away. I think we are getting close to it. Also, its easier to keep it at the client level as we can deploy faster. Not much of a reason but it'd require less work to maintain as that is a simple pull request where here we need to merge, test, deploy and restart the server.

**Comment by gaboesquivel** [comment]
I can hear you, ideally should go away. However it is still important IMO. 
The actual list could still be http://yeoman.io/blacklist.json, under the yeoman.io repo that has more subscribers too.  The actual filtering could be move to the this server, gaining some milliseconds :) on yeoman.io/generators and yo install ... although It could also be an insignificant/imperceivable difference.

another improvement here could be listing only the generators that meet the naming standards and other requirements, filtering programmatically, so that blacklisting becomes unnecessary for these cases.

**Comment by addyosmani** [comment]
> I think it would a good idea to filter the list on the server rather than filtering on each client.
filter generators and create a json file to be served. related to #19

:+1:

**Comment by eddiemonge** [comment]
It does have the name filter here: https://github.com/yeoman/yeoman-generator-list/blob/master/plugin-cache/src/npm-keyword-search.js#L22

**Comment by gaboesquivel** [comment]
good :+1: , I didn't notice you already added it
