### ISSUE TITLE
Subdomain for the list

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/yeoman-generator-list#33]
Be nice if we had something like list.yeoman.io for this (possibly https as well although don't know if that's needed)

**Comment by sindresorhus** [comment]
:+1: to both.

**Comment by hemanth** [comment]
:+1:

**Comment by sindresorhus** [comment]
@addyosmani Can you send a request for that?

**Comment by eddiemonge** [comment]
generators.yeoman.io ok to use? Any objections?

**Comment by sindresorhus** [comment]
:+1:

**Comment by eddiemonge** [comment]
@addyosmani can we get that subdomain setup?

**Comment by mischah** [comment]
Sorry, I’m confused. Are we talking about a subdomain for http://yeoman.io/generators/ or for the [JSON-file](https://cdn.rawgit.com/yeoman/yeoman-generator-list/cfbe7709ef6d0164fe7334052c9146fba32eaa66/cache.json)?

**Comment by eddiemonge** [comment]
The json-file like list. It should really be an api at some point

**Comment by mischah** [comment]
yeoman-generator-list isn’t in use any longer since https://github.com/yeoman/yeoman.github.io/pull/763 is merged. 

So this issue is obsolete 👋
