### ISSUE TITLE
Document how the list works

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/yeoman-generator-list#34]
Need to document how the list is generated and hosted, on what systems, how its updated, etc.

For now, the basics are:
DigitalOcean vps generates the list and pushes to:
Google Cloud Storage serves a static json list

**Comment by mischah** [comment]
Maybe @zckrs could jump in and and a few lines of documentation out of https://github.com/yeoman/yeoman-generator-list/pull/52 to the README?

**Comment by mischah** [comment]
yeoman-generator-list isn’t in use any longer since https://github.com/yeoman/yeoman.github.io/pull/763 is merged. 

So this issue is obsolete 👋
