### ISSUE TITLE
Block forked projects that have the same package.json

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/yeoman-generator-list#35]
If a project gets forked and doesn't update its package.json to be unique, then it should get blocked on the list.

**Comment by deepu105** [comment]
+1

**Comment by addyosmani** [comment]
👍

**Comment by mischah** [comment]
Is this still a valid issue after the huge changes of https://github.com/yeoman/yeoman-generator-list/pull/52?

**Comment by mischah** [comment]
yeoman-generator-list isn’t in use any longer since https://github.com/yeoman/yeoman.github.io/pull/763 is merged. 

So this issue is obsolete 👋
