### ISSUE TITLE
Notify package authors of problems

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/yeoman-generator-list#36]
If there is a problem with a package, notify its author to fix it. If the author doesn't have contact info, then it should notify a team member. 

At the very least, there should be a log of problem packages and what the problem is.

**Comment by eddiemonge** [comment]
KeyWordSearch: Skipping Blacklisted: generator-angular-js
KeyWordSearch: Skipping Blacklisted: generator-angular-phonegap
KeyWordSearch: Skipping Blacklisted: generator-angular-sparkstack
KeyWordSearch: Skipping Blacklisted: generator-charcoal
KeyWordSearch: Skipping Blacklisted: generator-express-angular
KeyWordSearch: Skipping Blacklisted: generator-ionicjs
KeyWordSearch: Skipping Blacklisted: generator-meteor-abtx
KeyWordSearch: Skipping Blacklisted: generator-mtb-app
KeyWordSearch: Skipping Blacklisted: generator-onereq
KeyWordSearch: Skipping Blacklisted: generator-polymer-plus
KeyWordSearch: Skipping Blacklisted: generator-react-coffee-webpack
KeyWordSearch: Skipping Blacklisted: generator-wordpress-bob
KeyWordSearch: Invalid name: generators-huya
KeyWordSearch: Invalid name: gram
KeyWordSearch: Invalid name: hajimetest
KeyWordSearch: Invalid name: hilojs
KeyWordSearch: Invalid name: imatic-stack
KeyWordSearch: Invalid name: in-directive
KeyWordSearch: Invalid name: ksofe-generator
KeyWordSearch: Invalid name: learning-yeoman-ch6
KeyWordSearch: Invalid name: lennon-generator-react-webpack
KeyWordSearch: Invalid name: muzzley-generator
KeyWordSearch: Invalid name: neat-starter-template
KeyWordSearch: Invalid name: ng-cli
KeyWordSearch: Invalid name: nick-site
KeyWordSearch: Invalid name: scaledrone-yo
KeyWordSearch: Invalid name: toolbox-utils
KeyWordSearch: Invalid name: webapp-slip
KeyWordSearch: Invalid name: yeoman-blender
KeyWordSearch: Invalid name: yeoman-generator-nick-site
KeyWordSearch: Invalid name: yeoman-meteor
KeyWordSearch: Invalid name: yeoman-ynote
KeyWordSearch: Invalid name: yirenyou-genorator
KeyWordSearch: Invalid name: yo-node-restify-aws-swagger

**Comment by mischah** [comment]
Is this still a valid issue after the huge changes of https://github.com/yeoman/yeoman-generator-list/pull/52?

**Comment by mischah** [comment]
yeoman-generator-list isn’t in use any longer since https://github.com/yeoman/yeoman.github.io/pull/763 is merged. 

So this issue is obsolete 👋
