### ISSUE TITLE
Generator not listed?

### ISSUE THREAD

**Issue by khalwat** [yeoman/yeoman-generator-list#38]
I posted this on `generator` a few weeks ago: https://github.com/yeoman/generator/issues/880

My generator still is not listed.  Did I do something wrong?

.....

I wrote a generator that has a GitHub repository description, and has yeoman-generator keyword and a description in package.json, but it's not being listed. What did I do wrong?

https://www.npmjs.com/package/generator-nystudio107

https://github.com/khalwat/generator-nystudio107

**Comment by SBoudrias** [comment]
cc @eddiemonge

**Comment by eddiemonge** [comment]
still working on getting the list to update. Kind of turned in to a refactor for the gen list. almost done

**Comment by khalwat** [comment]
Thanks.  I'm just trying to make sure I didn't do anything wrong on my end in terms of how/where my generator was listed.

**Comment by eddiemonge** [comment]
nope, not in the current problem list https://github.com/yeoman/yeoman-generator-list/issues/36

**Comment by eddiemonge** [comment]
Its there now.

**Comment by khalwat** [comment]
Thanks, it's there.  It looks like the Search function no longer looks at the descriptions, though, only the title.  So people looking for `Craft` will not find it.

Will it be reverted to the previous behavior of the list, and have it search the description too, or is this a permanent change?

**Comment by eddiemonge** [comment]
fixed the search in 94ff25290577f0c89e460a2ce998fc57e7733263
