### ISSUE TITLE
Handle Scoped packages

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/yeoman-generator-list#41]
^^

**Comment by addyosmani** [comment]
How badly do we break with slurping scoped packages today?

**Comment by eddiemonge** [comment]
I don't know if it does or not. Haven't tested any yet.

**Comment by mischah** [comment]
Is this still a valid issue after the huge changes of https://github.com/yeoman/yeoman-generator-list/pull/52?

**Comment by Myhlamaeus** [comment]
https://github.com/yeoman/yeoman-generator-list/blob/83cfd5e378eefbeaf76d627236d93c4ba0159271/src/npm-keyword-search.js#L15
https://github.com/yeoman/yeoman-generator-list/blob/c975f3e85ed4ef2abf3178d728e63ca58648bba9/src/npms-package-info.js#L59
These two parts are definitely not working with scopes.

**Comment by mischah** [comment]
yeoman-generator-list isn’t in use any longer since https://github.com/yeoman/yeoman.github.io/pull/763 is merged. 

So this issue is obsolete 👋
