### ISSUE TITLE
Non yeoman projects listed

### ISSUE THREAD

**Issue by deepu105** [yeoman/yeoman-generator-list#45]
Not sure if this is intentional or an issue, just opening in any case

Was searching for react generators and found that the top entry `react-fullstack` in that list as well as the all generators list is not even a yeoman generator, its a starter kit

Is this correct?

![fireshot capture 3 - generators i yeoman - http___yeoman io_generators_](https://cloud.githubusercontent.com/assets/1107223/12228524/9c4d0afe-b877-11e5-9070-81d71442ce30.png)

**Comment by eddiemonge** [comment]
It does or did have a generator in it. This came up in the past but we have left it for now

**Comment by deepu105** [comment]
Thats strange, I dont see any trace of yeoman in there its very misleading

**Comment by eddiemonge** [comment]
Its in a branch

**Comment by deepu105** [comment]
Thanks for the clarification, it wasnt obvious from main website page
