### ISSUE TITLE
Publish a list of problem packages

### ISSUE THREAD

**Issue by eddiemonge** [yeoman/yeoman-generator-list#46]
Related to #36 but should be a list where authors can see what the problem with the list is

**Comment by addyosmani** [comment]
Is the idea that we would publish a list that's viewable on-site / linked to from this repo every time a new deploy is done?

**Comment by eddiemonge** [comment]
Yeah

**Comment by mischah** [comment]
Is this still a valid issue after the huge changes of https://github.com/yeoman/yeoman-generator-list/pull/52?

**Comment by mischah** [comment]
yeoman-generator-list isn’t in use any longer since https://github.com/yeoman/yeoman.github.io/pull/763 is merged. 

So this issue is obsolete 👋
