### ISSUE TITLE
`generator-python-lib` Not Listed

### ISSUE THREAD

**Issue by hbetts** [yeoman/yeoman-generator-list#47]
Using http://yeoman.io/generators/ I'm unable to find `generator-python-lib`.

NPM package: https://www.npmjs.com/package/generator-python-lib

GitLab repository: https://gitlab.com/hutson/generator-python-lib

[package.json](https://gitlab.com/hutson/generator-python-lib/blob/master/package.json) includes a `description` and `yeoman-generator` in `keywords` list.

`generator-python-lib` appears in the following generator list: http://yeoman-generator-list.herokuapp.com/

However, it does not appear in https://storage.googleapis.com/generators.yeoman.io/cache.json

**Comment by SBoudrias** [comment]
cc @eddiemonge 

We might be lagging in our task queue.

**Comment by eddiemonge** [comment]
restarting it now

**Comment by eddiemonge** [comment]
Its possible its not showing because its on gitlab and not github. I'll have to research further to see why its not showing.

**Comment by hbetts** [comment]
@eddiemonge I can confirm that all `gitlab.com` based yeoman generators are **not** listed in https://storage.googleapis.com/generators.yeoman.io/cache.json

Though that list does, oddly, contain several projects hosted on private GitLab installations.

**Comment by eddiemonge** [comment]
Its in there, just needed a restart and an update to the server, but not related to the fact its on gitlab.
