### ISSUE TITLE
Question: which frequency refresh cache.json ?

### ISSUE THREAD

**Issue by zckrs** [yeoman/yeoman-generator-list#49]
Hi,

I see a desync between the https://storage.googleapis.com/generators.yeoman.io/cache.json and the generators on github (stars, version, etc).

How to update the list or which frequency update is done ?

**Comment by SBoudrias** [comment]
It's usually once a day, but the service ran into some issues where it needs to be manually launched. @eddiemonge has been in charge of the service for the past few months.

**Comment by diegohaz** [comment]
It has been stalled for more than a week 😞

**Comment by eddiemonge** [comment]
kicking it now
