### ISSUE TITLE
Proposal: Use a external API instead of fetch and parse data from multiple service

### ISSUE THREAD

**Issue by zckrs** [yeoman/yeoman-generator-list#50]
Hi,

Currently we make some HTTP requests from multiple service (npm and Github) and we encounter the problem of rate limit on Github due to existing more than 5000 yeoman-generator.

I would start a PR to use [npms.io](https://npms.io/) to replace this process and resolve issue.

What do you think about that?

---

[Example search call API](https://api.npms.io/v2/search?q=keywords%3Ayeoman-generator)

[Example package call API](https://api.npms.io/v2/package/generator-fountain-webapp)

**Comment by zckrs** [comment]
cache.json generate with npms.io in 439 seconds


https://gist.github.com/zckrs/5d8dcd3a5768862969e1fe2f44af5f54

**Comment by mischah** [comment]
Whoa 😳 👌🏼

**Comment by zckrs** [comment]
Should I continue in this direction or this proposal is reject?

Note: npms.io analyzed periodically packages from npm and GIthub so you can don't have real time info like stars and download count.

_Other drastic proposal would be to replace the generator list by a link to [npms.io](https://npms.io/search?q=keywords%3Ayeoman-generator) :trollface: _

/cc @SBoudrias  @eddiemonge

**Comment by zckrs** [comment]
Just drop a PR.

Currently http://yeoman.io/generators/ is totally broke. 

:-(

**Comment by eddiemonge** [comment]
What do you mean by totally broke?

**Comment by diegohaz** [comment]
@eddiemonge the default sort parameter of the list is "stars", which aren't fetched properly anymore. People looking for a generator will not see what they expect (unless they change the sort parameter).

A simple solution would be remove the stars column and change the default sort parameter to "Installs".

**Comment by zckrs** [comment]
I close my initial PR for a priceless solution without dependency to Google Cloud server.

https://github.com/yeoman/yeoman-generator-list/pull/52

**Comment by zckrs** [comment]
Merged
