### ISSUE TITLE
The generator list is gone

### ISSUE THREAD

**Issue by eligao** [yeoman/yeoman-generator-list#55]
Hi,
Your generator list on http://yeoman.io/generators/ is down.
The source of the list seems to be:
https://github.com/yeoman/yeoman-generator-list/blob/ca617b1ce2d797eb286e442034bd8766867192c3/cache.json
but it became empty after the latest CI update.
You might want to check this.

**Comment by zckrs** [comment]
Thanks for report. There is a problem with API npms.io

I will see detail and add a check to avoid this issue

**Comment by mischah** [comment]
@zckrs FYI. 

I saw that a PR of your is merged into the npms website repo.
But it’s still broken. https://npms.io/search?q=yeoman-generator

**Comment by zckrs** [comment]
fixed
