### ISSUE TITLE
Move the processing of the data to a background task.

### ISSUE THREAD

**Issue by ericduran** [yeoman/yeoman-generator-list#6]
Once https://github.com/yeoman/yeoman-generator-list/pull/5 gets in the initial request for the json feed will take around 15seconds :-/ because of all the http request.

We can instead just add a background job (https://addons.heroku.com/scheduler) that does all the processing and stores the data somewhere denormalized.

This way we could just make a simple request in mongolab or something to get all the data. This should bring that initial request to something reasonable.

I'll start working on this soon.

**Comment by SBoudrias** [comment]
Having a separate task to fetch data is the way to go.

Node.js being async, there's no real need for an extra scheduler. We can simply rely on a timer to refresh data at every n time internal.

Then we should cache this data in a file or a cache somewhere. So we can rely on previous data when we start failing to fetch.

**Comment by sindresorhus** [comment]
:+1:

**Comment by SBoudrias** [comment]
Added a dummy timer based in memory cache. Hopefully that'll fix our uptime issues.
